name: Java Quality Checks

permissions:
  contents: write

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main   # Trigger only on PRs targeting the main branch

jobs:
  spotless-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Apply Spotless formatting
        run: mvn spotless:apply
      - name: Commit changes if any
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "Apply Spotless formatting"
          git push origin HEAD:${{ github.head_ref }}

  checkstyle:
    needs: spotless-apply
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: mvn checkstyle:check

  spotbugs:
    needs: spotless-apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Run SpotBugs
        run: mvn spotbugs:check

  tests:
    needs: spotless-apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Run Unit Tests
        run: mvn test

  compile:
    needs: spotless-apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Compile all Java files
        run: |
          mkdir -p bin
          javac -d bin $(find . -name "*.java")

  run-main:
    needs: spotless-apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Run main class
        run: |
          mkdir -p out
          javac -d out *.java
          java -cp out your.package.MainClass || true
